### ISSUE TITLE
Error while querying the chaincode

### ISSUE THREAD

**Issue by tukarthik** [yeasy/docker-hyperledger#2]
Hi,

I have deployed 4 peers with docker-compose.yml that's provided.
I am successful in deploying the chaincode_example02 on to the blockchain.

However, when I try to query the blockchian for the values, I am getting error. The error is
 **Error when querying chaincode: Error:Failed to launch chaincode spec(Could not get deployment transaction for cfa4c2a2b83e296526d2ea3a2e03ef0065a69605a4c01a8111571d7de0704a2d67a7ec01952243ef0b214a7bce0dc0d53733e32dc43c796b95a923bb8348e014 - LedgerError - ResourceNotFound: ledger: resource not found)"**

Please help me.

**Comment by yeasy** [comment]
What version of image are u using?
Can u tell the whole steps to repeat?
Thanks!

**Comment by tukarthik** [comment]
Hi,

I have attached the console commands that I used.
I deployed the chaincode and i got the hash for it.
But, when i was parallely looking at the logs (docker attach logs), i was getting an error. (see attached file)
I am not able to find the cause for it.
Kindly help.

[Console Commands.txt](https://github.com/yeasy/docker-hyperledger/files/600512/Console.Commands.txt)
[Deploy Error.txt](https://github.com/yeasy/docker-hyperledger/files/600511/Deploy.Error.txt)
[docker-compose.yml.txt](https://github.com/yeasy/docker-hyperledger/files/600547/docker-compose.yml.txt)
[peer-pbft.yml.txt](https://github.com/yeasy/docker-hyperledger/files/600548/peer-pbft.yml.txt)

Thanks,
Karthik TU

**Comment by yeasy** [comment]
Hi after a quick check, I notice you're using the latest image, which is not stable currently.

Can you try using this one: https://hub.docker.com/r/yeasy/hyperledger-fabric/tags/, use the 0.6-dp tag.

Thanks!

**Comment by biksen** [comment]
Hi,
I am using Docker Toolbox for Windows 7. I am using your Dockerfile to build hyperledger fabric docker image. But when I am executing the following docker build command within docker CLI terminal, I am getting an error: Please find the attached Dockerfile and find the below error: I have already set GOPATH windows environment variable to "C:\gohome"

**Command**:: docker build -t biksen/hyperledger .

**Error**:: ---> Running in a4d1d3f54fd9
Cloning into 'fabric'...
/bin/sh: 1: cd: can't cd to /go/src/github.com/hyperledger/fabric/membersrvc
The command '/bin/sh -c mkdir -p $GOPATH/src/github.com/hyperledger         && cd $GOPATH/src/github.com/hyperledger         && git clone --single-branch -b master --depth 1 http://gerrit.hyperledger.
org/r/fabric         && cd $GOPATH/src/github.com/hyperledger/fabric/peer         && CGO_CFLAGS=" " CGO_LDFLAGS="-lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy" go install         && go clean         && cd
 $GOPATH/src/github.com/hyperledger/fabric/membersrvc         && CGO_CFLAGS=" " CGO_LDFLAGS="-lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy" go install         && go clean         && cp $GOPATH/src/github.
com/hyperledger/fabric/devenv/limits.conf /etc/security/limits.conf' returned a non-zero code: 2
[Dockerfile.txt](https://github.com/yeasy/docker-hyperledger/files/722196/Dockerfile.txt)

**Comment by biksen** [comment]
Hi,

The above problem has been resolved. I have changed hyperledger version from latest to v0.6. Now I am facing another problem. I have created a GO chaincode and I am REST API to interact with my chaincode. Registrar, Deploy and Invoke is working fine through REST but Query is NOT working. Please find the attached docker compose file for your reference. Any help will be greatly appreciated!

**Error**:: "message": "Query failure",
    "data": "Error when querying chaincode: Error:Failed to launch chaincode spec(Could not get deployment transaction for 4b8875714939d34c12647ae8753046adc12eba5fb11ec478882081bead6dfdbd5852c316f71b6c786fbcbf53082bbd93aeb00f5b3eea44e828c881fef26826a8 - LedgerError - ResourceNotFound: ledger: resource not found)"
[docker-compose.yml.txt](https://github.com/yeasy/docker-hyperledger/files/722644/docker-compose.yml.txt)

**Comment by yeasy** [comment]
It seems sth wrong with the env, then the chaincode container cannot start.

First, pls DONOT use windows env.

Both linux and macos should work.
